Single post view
WordPress/wporg-news-2021 pull request #21
Opened 2021-08-24 22:44 UTC by coreymckrill

WIP

Fixes #17

2021-08-26 17:54 UTC, iandunn requested changes
The Grid and `SCRIPT_DEBUG` comments seem important to discuss more before merging, but I don't feel strongly about the others.

2021-08-26 17:54 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/block-template-parts/content-single.html
> +	<header class="wp-block-group alignwide entry-header">
🤔 , is this a template that users will be able to edit?

If not, should we still use `group` blocks, etc, instead of just having `div`s?

It seems like we'd only need "content" blocks like `core/audio`, and functional ones like `core/query`, but the markup could just be regular HTML. That would cut down on the "comment soup" and make things more human readable.

2021-08-26 17:54 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
>  @import "blocks/paragraph";
Not directly related to this PR, but what's the reason to name this `ponyfill`? Was that a Blockbase artifact?

It seems like it's just the SASS index file; is it trying to say that it's ponyfilling all the missing CSS features like mixins etc?

It's kind of confusing, I think it'd be more intuitive to name it `style.scss`, `style.css`, `wporg-news-2021-style`, etc.

I can rename it after this PR is merged, if that sounds good to you.

2021-08-26 17:54 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
Huh, it looks like this when `SCRIPT_DEBUG` is `false`, but correct when it's `true`:

![Screen Shot 2021-08-26 at 9 26 20 AM](https://user-images.githubusercontent.com/484068/131000123-93187bd7-266b-47ee-8349-5cd2ba56c11e.png)

🤔

2021-08-26 17:54 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +	.single .wp-block-post-content > * {
```suggestion
	body.single .wp-block-post-content > * {
```

otherwise it's not clear which `.single` it's referring to

2021-08-26 17:54 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
Is there a simpler way to do this? It doesn't feel like it should need to be the this complicated.

would grid be a better fit for all the layout? my understanding is that flexbox isn't really designed for that.

2021-08-26 22:34 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/block-template-parts/content-single.html
> +	<header class="wp-block-group alignwide entry-header">
I don't anticipate that this will be editable now. But I think it would be a mistake to make it incompatible (or at least less compatible) with FSE if that were to change in the future. I honestly don't think the legibility is impacted that much.

2021-08-26 22:35 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
>  @import "blocks/paragraph";
Yeah, that's an artifact from Blockbase. I'm fine renaming it, I agree it's kind of weird and confusing. 👍

2021-08-26 22:36 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
That's odd, I'll see if I can replicate that...

2021-08-26 22:40 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
>  @import "blocks/paragraph";
👍🏻 , i'll do that after this is merged.

2021-08-26 22:40 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
huh, as long as it doesn't happen in production then I wouldn't worry about it 🤷🏻‍♂️

2021-08-26 22:43 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
Oh, I misread that, you said you were going to try to replicate, not that you'd tried and couldn't :)

2021-08-26 22:45 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
I can't reproduce this. I set `SCRIPT_DEBUG` to `false` in .wp-env.json and then confirmed that the constant was set to false on the front end, but the styles were still loading correctly...

2021-08-26 22:47 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +	.single .wp-block-post-content > * {
🤔 Where else is `single` used in a different context?

2021-08-26 22:51 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +	.single .wp-block-post-content > * {
I can't think of one off the top of my head, but it seems common enough that a plugin etc could use it.

The main benefit IMO is the clarity, so someone isn't left asking "where does that come from? i don't see it anywhere in the theme...", and then have to dig around before they remember the body classes.

Not a big deal though

2021-08-26 22:51 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/ponyfill.scss
> +@import "post/header";
👍🏻 , probably some quirk in my env then

2021-08-26 23:09 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
I couldn't think of a simpler way to ensure that the content column is responsively aligned on the right side, instead of centered, while still allowing individual blocks with `wide` or `full` alignment to expand appropriately.

This isn't actually using flexbox, just margins (same way Blockbase aligns content). I considered using flexbox, but it breaks things like having a left-aligned image with paragraph text wrapping around it. Plus it doesn't play well with the `.wp-container-[hash]` styles that get output automatically at the end of the document based on the `layout.contentSize` value in theme.json.

I haven't used CSS Grid much, but my understanding is that it doesn't work that well when you have an unknown number of elements in the grid. Plus I suspect it would have the same issues as flexbox regarding breaking some layouts...

2021-08-27 00:00 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
> This isn't actually using flexbox, just margins

I meant that `.entry-header`, `.entry-content` and `.post-navigation` are all creating identical columns, and the "like/share" section will too. This section is using margins to do it, but the others use Flex.

If we setup a Grid, though, they'd all automatically inherit the columns, rather than each one having to define them explicitly using various (and sometimes complication) methods.

> still allowing individual blocks with wide or full alignment to expand appropriately.

🤔 , I would think that should still work, but I can play around w/ it tomorrow.

> [grid might] breaks things like having a left-aligned image with paragraph text wrapping around it

I don't think that'd happen, since the grid styles wouldn't be inherited by the contents inside each cell

> [grid might not] play well with the `.wp-container-[hash]` styles 

🤔 , I see those in the source, but don't see them actually applying to anything. I'll see what happens when I play around w/ it tomorrow.


> it doesn't work that well when you have an unknown number of elements in the grid

I was picturing we'd use it to define the layout at a higher level, rather than the individual paragraphs. i.e.,

<table>
<tr> <td colspan="2">header</td> </tr>
<tr> <td colspan="2">local nav</td> </tr>
<tr> <td>entry meta</td> <td>entry title</td> </tr>
<tr> <td></td> <td>entry content</td> </tr>
<tr> <td>share</td> <td>like</td> </tr>
<tr> <td>previous</td> <td>next</td> </tr>
<tr> <td colspan="2">footer</td> </tr>
</table>

So we'd have a defined # of elements.

2021-08-27 16:44 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
I played around w/ it for a couple hours, but the big problem I ran into is that we really need Subgrid to make the (great-)grandchild elements of the grid container conform to the grid areas. [It's still not well supported](https://caniuse.com/?search=subgrid), though.

[`display:contents` could work](https://stackoverflow.com/questions/48050939/what-is-an-alternative-to-css-subgrid), but it's [hacky](https://rachelandrew.co.uk/archives/2017/07/20/why-display-contents-is-not-css-grid-layout-subgrid/) and also [not well enough supported](https://caniuse.com/css-display-contents).

IMO there are some excessive containers that could be removed, but many are semantically appropriate, and removing those would also be hacky.

Nested grids might work, but I don't think there's a significant enough benefit to make the time investment, since you've already got the flex/margin approach working.

So yeah, this seems good enough 👍🏻 

Some comments on the complex lines like this would be really appreciated, though -- both the _what_, and the _why_.

2021-08-27 16:47 UTC, iandunn approved these changes
The comments would be great, but not a blocker. Thanks!

2021-08-27 19:20 UTC, coreymckrill commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
Good idea. Comments added in 0488417

2021-08-27 19:22 UTC, merged

2021-08-27 20:04 UTC, iandunn commented on source/wp-content/themes/wporg-news-2021/sass/blocks/_post-content.scss
> +		) !important;
Thanks!